name:                madop
version:             0.1.0.0
github:              "pottu/madop"
license:             BSD3
author:              "Pontus Ernstedt"
copyright:           "2019 pottu@github"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/pottu/madop#readme>

dependencies:
- base >= 4.7 && < 5
- mtl
- parsec

library:
  source-dirs: src

executables:
  madop:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - madop

tests:
  madop-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - madop
